title: Emergence Docs
description: Documentation of Crucible's Emergence plugin
theme: just-the-docs
color_scheme: dark

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


url: https://just-the-docs.github.io

aux_links:
  Unreal Github: https://github.com/CrucibleNetworksLtd/EmergenceSDKUnreal
  Fab: https://www.fab.com/listings/663187a7-fe59-4fe0-a4aa-cb6582d8842f
  Unity Asset Store: https://assetstore.unity.com/packages/decentralization/infrastructure/emergence-sdk-252187
